# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Clone and push'
          script:
            - echo "Creating a local mirror of the Bitbucket repository"
            # - git clone --mirror ${BITBUCKET_URL} repo-mirror
            
            - echo "Syncing the Bitbucket repository with GitHub"
            - 
            - echo "The token will expire on Sat, Oct 15 2022"
